# This is a basic workflow to help you get started with Actions

name: CI
On: workflow_discpatch
jobs:
 first_job:
  runs-on: ubuntu_latest
  steps:
   -name: Test
    run: echo "Hello World"
   -name: Test2
    run: echo "bye"
